# Generated by Django 2.1.1 on 2018-10-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
