# Generated by Django 2.1.1 on 2018-10-04 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0004_social_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='user',
            new_name='profile',
        ),
    ]
