# Generated by Django 2.1.1 on 2018-10-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0005_auto_20181004_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
