# Generated by Django 2.1.1 on 2018-10-04 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0006_auto_20181004_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 4, 7, 29, 0, 529641)),
        ),
    ]
